In [116]:
import numpy as np

In [2]:
a = np.zeros(4)
a = np.zeros((4,3,2,2))

In [3]:
a = np.random.random_sample((4, 4))
a

array([[0.89949313, 0.91776883, 0.65098175, 0.60615319],
       [0.50413939, 0.20263417, 0.88348878, 0.2635576 ],
       [0.88697613, 0.54812504, 0.80784446, 0.84850249],
       [0.46614289, 0.87232742, 0.59657205, 0.08507029]])

In [4]:
a[][3]

SyntaxError: invalid syntax (3855398949.py, line 1)

In [5]:
a.shape

(4, 4)

In [6]:
a.ndim

2

In [7]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d.ndim

3

In [8]:
arr = np.array([1,2,3,4], ndmin=5)
arr.ndim

5

In [9]:
arr[0][0]

array([[[1, 2, 3, 4]]])

In [10]:
ds = np.array([[1,2,3,4],[5,6,6,7]])
ds[0,-1]

np.int64(4)

In [11]:
dk = np.arange(4.)
dk

array([0., 1., 2., 3.])

In [12]:
kl = np.random.rand(4)
kl

array([0.33513538, 0.96114382, 0.41014034, 0.3317735 ])

In [13]:
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


Basic command to initialize a ndarray

In [14]:
a = np.array([1,2,4])
a

array([1, 2, 4])

In [15]:
a = np.array([[1,2,3],[15,6,7]])
a

array([[ 1,  2,  3],
       [15,  6,  7]])

initializing array using zero as placeholder

In [16]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [17]:
a = np.zeros((4,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

initializing array using one

In [18]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [19]:
a = np.int64(np.ones((4,3)))
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

initializing array using arange function (start,stop,step)

In [20]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [21]:
a = np.arange(4,8)
a

array([4, 5, 6, 7])

In [22]:
a = np.arange(4,8,2)
a

array([4, 6])

In [31]:
a = np.arange(24).reshape(-1,4,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [24]:
a.ndim

3

Initializing array using linspace function (start, stop, num). Gives you equal spaces numbers has mention in the num

In [25]:
a = np.linspace(2, 10)
a

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [26]:
a.shape

(50,)

initializing array using random

In [27]:
a = np.random.rand(6)
a #in the range 0 to 1

array([0.14110107, 0.27985803, 0.58161887, 0.81287066, 0.40115362,
       0.94810332])

In [28]:
a = np.random.randn(20)
a

array([-0.32105811, -0.31423245,  0.99453387, -2.06181484,  0.95431292,
        1.07396294,  0.8457467 , -1.78893053, -0.32639615, -1.10593978,
       -0.48824923, -0.17278567,  1.15255647,  2.10779343, -1.14744997,
       -0.44357967, -2.03471303, -0.18211001, -0.14609562,  0.06848179])

In [29]:
np.random.seed(43)
a = np.random.randint(0,30,4)
a

array([ 4,  0, 17, 21], dtype=int32)

Array attributes

In [32]:
a.shape

(2, 4, 3)

In [33]:
a.size

24

In [34]:
a[0,1,:].size

3

In [35]:
a.itemsize

8

In [38]:
s = np.array(["a", "bb", "cc"])
s

array(['a', 'bb', 'cc'], dtype='<U2')

In [39]:
s.itemsize

8

Datatypes in numpy

In [40]:
a = np.array([1.7, 2.9, 3.1])

In [41]:
a.astype("int")

array([1, 2, 3])

In [42]:
a.astype("float")

array([1.7, 2.9, 3.1])

In [44]:
a.astype("bool")

array([ True,  True,  True])

In [47]:
a = np.array(20, dtype=np.int8)

Array indexing and slicing

In [48]:
a = np.array([10, 20, 30, 40, 50])

In [52]:
print(a[1:3])
print(a[:-1])
print(a[::2])
print(a[::-1])

[20 30]
[10 20 30 40]
[10 30 50]
[50 40 30 20 10]


In [54]:
print(a[1:5:2])

[20 40]


In [64]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

In [56]:
print(a[0][3])
print(a[:,1])
print(a[-1,:])

4
[ 2  6 10]
[ 9 10 11 12]


In [57]:
print(a[0:2, 1:-1])

[[2 3]
 [6 7]]


In [58]:
print(a[-1])
print(a[-1,-1])
print(a[:, -1])

[ 9 10 11 12]
12
[ 4  8 12]


In [59]:
a = np.array([10, 25, 3, 47, 8, 31])

In [61]:
mask = a > 25
print(mask)
a[mask]

[False False False  True False  True]


array([47, 31])

In [62]:
a[a>20]

array([25, 47, 31])

In [63]:
a[[1,1,2,4]]

array([25, 25,  3,  8])

In [65]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a[:, [0,2]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [67]:
b = a[:, [0,2]]
b

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [68]:
b[0,0]=2

In [69]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
b

array([[ 2,  3],
       [ 5,  7],
       [ 9, 11]])

In [71]:
b = a[0,:]

In [72]:
b

array([1, 2, 3, 4])

In [73]:
b[0] = 8

In [74]:
b

array([8, 2, 3, 4])

In [75]:
a

array([[ 8,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
a.size

12

In [78]:
a = np.arange(42).reshape(2,3,7)

In [79]:
a

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]]])

In [80]:
b = a.flatten()

In [81]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [82]:
b[1] = 100

In [83]:
b

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41])

In [84]:
a

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]]])

In [85]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [86]:
b[1] = 100
a

array([[[  0, 100,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12,  13],
        [ 14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27],
        [ 28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41]]])

In [87]:
a.T

array([[[  0,  21],
        [  7,  28],
        [ 14,  35]],

       [[100,  22],
        [  8,  29],
        [ 15,  36]],

       [[  2,  23],
        [  9,  30],
        [ 16,  37]],

       [[  3,  24],
        [ 10,  31],
        [ 17,  38]],

       [[  4,  25],
        [ 11,  32],
        [ 18,  39]],

       [[  5,  26],
        [ 12,  33],
        [ 19,  40]],

       [[  6,  27],
        [ 13,  34],
        [ 20,  41]]])

In [88]:
a.shape

(2, 3, 7)

In [89]:
a

array([[[  0, 100,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12,  13],
        [ 14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27],
        [ 28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41]]])

In [90]:
b = a.T

In [91]:
b.shape

(7, 3, 2)

In [92]:
b = a.transpose(0,1,2)
b

array([[[  0, 100,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12,  13],
        [ 14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27],
        [ 28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41]]])

In [93]:
b = a.transpose(1,0,2)
b

array([[[  0, 100,   2,   3,   4,   5,   6],
        [ 21,  22,  23,  24,  25,  26,  27]],

       [[  7,   8,   9,  10,  11,  12,  13],
        [ 28,  29,  30,  31,  32,  33,  34]],

       [[ 14,  15,  16,  17,  18,  19,  20],
        [ 35,  36,  37,  38,  39,  40,  41]]])

In [108]:
a = np.array([1, 2, 3])  
np.expand_dims(a, axis=0)

array([[1, 2, 3]])

In [113]:
b = np.expand_dims(a, axis=0)
b.shape

(1, 3)

In [101]:
np.expand_dims(b, axis = 1)

array([[[1]],

       [[2]],

       [[3]]])

In [102]:
b.shape

(3, 1)

In [104]:
c = np.squeeze(b)

In [105]:
c.shape

(3,)

In [115]:
c = np.squeeze(b, axis=0)
c.shape

(3,)