In [1]:
import numpy as np

In [8]:
a = np.zeros(4)
a = np.zeros((4,3,2,2))

In [21]:
a = np.random.random_sample((4, 4))
a

array([[0.02561731, 0.29126228, 0.87574846, 0.70640971],
       [0.37978363, 0.48805364, 0.36628097, 0.7869088 ],
       [0.88543084, 0.49759579, 0.41615855, 0.5239691 ],
       [0.46008436, 0.58323804, 0.43640975, 0.25563023]])

In [18]:
a[][3]

In [23]:
a.shape

(4, 4)

In [24]:
a.ndim

2

In [25]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d.ndim

3

In [27]:
arr = np.array([1,2,3,4], ndmin=5)
arr.ndim

5

In [31]:
arr[0][0]

array([[[1, 2, 3, 4]]])

In [34]:
ds = np.array([[1,2,3,4],[5,6,6,7]])
ds[0,-1]

np.int64(4)

In [36]:
dk = np.arange(4.)
dk

array([0., 1., 2., 3.])

In [37]:
kl = np.random.rand(4)
kl

array([0.53177451, 0.70314521, 0.28687374, 0.07652401])

In [38]:
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64
